/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'agenda': RouteRecordInfo<'agenda', '/agenda', Record<never, never>, Record<never, never>>,
    'agentes': RouteRecordInfo<'agentes', '/agentes', Record<never, never>, Record<never, never>>,
    'asegurados': RouteRecordInfo<'asegurados', '/asegurados', Record<never, never>, Record<never, never>>,
    'catalogos-actividades': RouteRecordInfo<'catalogos-actividades', '/catalogos/actividades', Record<never, never>, Record<never, never>>,
    'catalogos-companias': RouteRecordInfo<'catalogos-companias', '/catalogos/companias', Record<never, never>, Record<never, never>>,
    'catalogos-estatus-clientes': RouteRecordInfo<'catalogos-estatus-clientes', '/catalogos/estatus-clientes', Record<never, never>, Record<never, never>>,
    'catalogos-lineas': RouteRecordInfo<'catalogos-lineas', '/catalogos/lineas', Record<never, never>, Record<never, never>>,
    'catalogos-metodo-pago': RouteRecordInfo<'catalogos-metodo-pago', '/catalogos/metodo-pago', Record<never, never>, Record<never, never>>,
    'catalogos-tipos-usuarios': RouteRecordInfo<'catalogos-tipos-usuarios', '/catalogos/tipos-usuarios', Record<never, never>, Record<never, never>>,
    'catalogos-tipos-vencimiento': RouteRecordInfo<'catalogos-tipos-vencimiento', '/catalogos/tipos-vencimiento', Record<never, never>, Record<never, never>>,
    'clientes': RouteRecordInfo<'clientes', '/clientes', Record<never, never>, Record<never, never>>,
    'cotizaciones': RouteRecordInfo<'cotizaciones', '/cotizaciones', Record<never, never>, Record<never, never>>,
    'cotizaciones copy': RouteRecordInfo<'cotizaciones copy', '/cotizaciones copy', Record<never, never>, Record<never, never>>,
    'denegado': RouteRecordInfo<'denegado', '/denegado', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'polizas': RouteRecordInfo<'polizas', '/polizas', Record<never, never>, Record<never, never>>,
    'promotores': RouteRecordInfo<'promotores', '/promotores', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
  }
}
